### ISSUE TITLE
Trying to understand the oauth2 scope and how security works

### ISSUE THREAD

**Issue by KarimJedda** [hjacobs/connexion-example#1]
Hi there,

I'm soon publishing a blog post about how to use this library, I'm still missing a point though, how does the security work?
I have my project in pycharm and before starting your example I set HTTP_TOKENINFO_URL=https://auth.example.org/tokeninfo as global variable but I don't know what I am missing. I absolutely don't know what I am doing and I'd be glad to get some help here.. 
Thanks a lot!

Alternatively, how would I set up a simple "password"?

**Comment by hjacobs** [comment]
By setting the environment variable `HTTP_TOKENINFO_URL` (or `x-tokenInfoUrl` on the security definition) you will simply enable the security decorator which will request the given HTTP URL with an `access_token` parameter filled with the `Bearer` token (https://github.com/zalando/connexion/blob/master/connexion/decorators/security.py#L64) and extracts the JSON response. The JSON response must contain the fields `scope` and `uid` (e.g. username).

I'm not familiar with standard security mechanisms in Flask, but you can always simply decorate your function with a custom function to do security checking. You can find a simple example here: http://flask.pocoo.org/snippets/8/

**Comment by hjacobs** [comment]
@KarimJedda I added a very simple example of HTTP Basic Auth here: https://github.com/zalando/connexion/tree/master/examples/basicauth

**Comment by hjacobs** [comment]
@KarimJedda I also added a simple OAuth2 resource server example with a mock token info endpoint: https://github.com/zalando/connexion/tree/master/examples/oauth2

**Comment by hjacobs** [comment]
@KarimJedda obviously I would like to see your published blog post :smile: 

Don't hesitate to ask/contact if you need any further support. Thanks!

**Comment by KarimJedda** [comment]
Wow @hjacobs, I wasn't expecting such a wonderful and detailled answer, thanks a lot !!! I will try it out right away. Really man you're doing some awesome job with this! 
Sure thing, you'll be the first to know when it's done ;) 
thanks again!!
