### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by marble** [hjacobs/connexion-example#6]
I had to spend much time yesterday and today trying to get several software packages up and running. Mostly without full success. Frustrating. But I tried this one and it DOES work as promised right out of the box, with Docker. Hooray! You're saving my day! Your work is totally in line with what I had unausgegoren (totally unready) in my head. I'm so happy the last meetup had pointed me to this direction. Happy Christmas!
https://www.meetup.com/de-DE/monster-tech-tales-software-engineering-user-group-muenster/events/235728759/

**Comment by hjacobs** [comment]
@marble cool, thanks --- I just checked the slides :smile:

**Comment by marble** [comment]
If I get it right: connexion does not generate an (initial) app.py?
Are you available for (sporadic) questions on a Slack channel or another channel?

**Comment by hjacobs** [comment]
Yes, Connexion will not generate an initial `app.py`, but you can use the CLI to run with mocks/stubs: https://connexion.readthedocs.io/en/latest/cli.html
