### ISSUE TITLE
Default values for animal fields

### ISSUE THREAD

**Issue by worldmind** [hjacobs/connexion-example#8]
Hello, thank for good example.
I am try set default values for not required fields, I remove
`pet['created'] = datetime.datetime.utcnow()`
from code and add
`--- a/swagger.yaml`
`+++ b/swagger.yaml`
`@@ -115,9 +115,9 @@ definitions:`
`        format: date-time`
`        description: Creation time`
`        example: "2015-07-07T15:49:51.230+02:00"`
`        {+default: "2015-07-07T15:49:51.230+02:00"+}`
but it does not work, I read [this](http://swagger.io/unlocking-the-spec-the-default-keyword/) and try different variants, but nothing work.
It is swagger/connexion bug or it is bug in my understanding?

**Comment by hjacobs** [comment]
@worldmind I think `default` makes no sense here as the `created` property should be the actual creation time, not some fixed default value.

**Comment by worldmind** [comment]
I understand, i use this field just for example

**Comment by hjacobs** [comment]
@worldmind yes, Connexion does only process `default` for parameters, but not for (nested) object definitions. You can report a bug in Connexion for this.

**Comment by worldmind** [comment]
Ok, thanks, issue [here](https://waffle.io/zalando/connexion)

**Comment by hjacobs** [comment]
Issue reported in Connexion: https://github.com/zalando/connexion/issues/375
